### ISSUE TITLE
Plugin breaks when a referred image file is missing

### ISSUE THREAD

**Issue by AdrianSorop** [oxygenxml/Translation-Package-Builder#14]
In my map structure I have an external reference to a missing image file.
When the "Generate Milestone" is called, the plugin fails to generate the translation report. 
Error is :
Milestone creation failed because of: path/to/file/imageName.png 
(The system cannot find the file specified)"

**Comment by AdrianSorop** [comment]
at com.oxygenxml.translation.support.core.MilestoneUtil.generateMD5(MilestoneUtil.java:69)
	at com.oxygenxml.translation.support.core.resource.MapStructureResourceBuilder$SaxResource.getResourceInfo(MapStructureResourceBuilder.java:128)
	at com.oxygenxml.translation.support.core.ChangePackageGenerator.computeResourceInfo(ChangePackageGenerator.java:93)
	at com.oxygenxml.translation.support.core.ChangePackageGenerator.computeResourceInfo(ChangePackageGenerator.java:99)
	at com.oxygenxml.translation.support.core.ChangePackageGenerator.computeResourceInfo(ChangePackageGenerator.java:99)
	at com.oxygenxml.translation.support.core.ChangePackageGenerator.generateChangeMilestone(ChangePackageGenerator.java:272)
	at com.oxygenxml.translation.ui.worker.GenerateMilestoneWorker.doInBackground(GenerateMilestoneWorker.java:28)
	at com.oxygenxml.translation.ui.worker.GenerateMilestoneWorker.doInBackground(GenerateMilestoneWorker.java:1)

**Comment by AlexJitianu** [comment]
A missing file signals a problem in the map structure but the plugin shouldn't crash.  I suggest we report a warning in the results area and generate the milestone without that missing file. There is an API for contributing to the results area: [ResultsManager](https://www.oxygenxml.com/InstData/Editor/SDK/javadoc/ro/sync/exml/workspace/api/PluginWorkspace.html#getResultsManager--)

**Comment by AdrianSorop** [comment]
When the a file is missing the plugin will not crash and the file will be reported int the "Translation Package Builder" results pane.
